### ISSUE TITLE
Pauta Encontro #01 (05/04/2018) Assunto: Promises e async/await

### ISSUE THREAD

**Issue by fdaciuk** [queroserninja/meetups#3]
Sugira ideias de assuntos para falarmos no nosso primeiro encontro (uma ideia por comentário, para facilitar a votação)!

Vote na ideia que você gostaria de discutir / ouvir sobre no nosso encontro com um :+1: =)

**Comment by adeonir** [comment]
Closure

**Comment by fdaciuk** [comment]
Imutabilidade em JavaScript

**Comment by manzoliric** [comment]
Aplicando JavaScript em projetos reais

**Comment by fdaciuk** [comment]
Promises

**Comment by fdaciuk** [comment]
Async / await

**Comment by AzevedoDev** [comment]
Call backs e sua importância

**Comment by Jciel** [comment]
Programação Funcional com JavaScript

**Comment by alinebastos** [comment]
Principais causas de erros ao escrever um código em JavaScript.

**Comment by SilvaAriel** [comment]
Estruturando o pensamento na solução de problemas.

**Comment by alinebastos** [comment]
Como fazer o código para decidir data, horário e assunto, baseado nas issues:
https://codesandbox.io/s/llq4wm3r99

**Comment by Morette** [comment]
Prototype

**Comment by pamplonapaulo** [comment]
'callback hell'

**Comment by RafaelSantannaGomez** [comment]
JavaScript em projetos reais

**Comment by allyssonsantos** [comment]
Server side rendering com styled-components
