### ISSUE TITLE
Pauta Encontro #02 (07/06/2018) Assunto: Imutabilidade em JavaScript

### ISSUE THREAD

**Issue by fdaciuk** [queroserninja/meetups#5]
Sugira ideias de assuntos para falarmos no nosso segundo encontro *(uma ideia por comentário, para facilitar a votação)*!

Vote na ideia que você gostaria de discutir / ouvir sobre no nosso encontro com um :+1: =)

PS.: Várias ideias legais foram sugeridas para o [`Encontro #01`](https://github.com/queroserninja/meetups/issues/3). Fique à vontade para sugerir novamente alguma dessa lista que não ainda não foi escolhida =)

**EDIT:** Link da transmissão: https://youtu.be/_NdkrfKJh7g

**Comment by matheusmazeto** [comment]
Fluxo de trabalho da sua empresa.

**Comment by antoniotex** [comment]
REST API

**Comment by fdaciuk** [comment]
Imutabilidade em JavaScript

**Comment by fdaciuk** [comment]
Prototype e class

**Comment by adeonir** [comment]
Closure

**Comment by alexandre1202** [comment]
Arquiteturas de referencias para times de Frontend ou Full Stack usando ReactJS

**Comment by gabrielferreiraa** [comment]
SSR

**Comment by eduardofg87** [comment]
Java

**Comment by nidelson** [comment]
TypeScript: Tipagem

**Comment by clarabatt** [comment]
Protocolos de Comunicação

**Comment by fdaciuk** [comment]
Como servir CSS em libs feitas com React
